name: Deploy Static Site

on:
  push:
    branches:
      - main  # Change if using another branch

permissions:
  contents: write  # Required for GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Change this if your site is inside a folder (e.g., `dist/`)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
